DATA SEGMENT 
	HC 	DB 0DH,0AH,'$';回车换行
	SR	DB 60
		DB ?
		DB 60 DUP(20H)
	TS	DB 'Please input string:',0DH,0AH,'$'
	TS2 DB 0DH,0AH,'This string is :$'
	FI	DB 'Press any key to countinue!$'
DATA ENDS
CODE SEGMENT 
	ASSUME DS:DATA,CS:CODE
OUTPUTSTR MACRO STR;输出字符串的宏
		LOCAL NEXT
		MOV CL, STR+1
		LEA SI, STR+2
	NEXT:
		MOV DX, [SI]
		MOV AH, 2
		INT 21H
		INC SI
		DEC CL
	JNZ NEXT
	ENDM
MAIN PROC FAR
	MOV AX, DATA
	MOV DS, AX ;ASSUME只是定义了段寄存器和逻辑段之间的关系，需要通过MOV指令赋初值
	LEA DX, TS;提示输入字符串
	CALL OUTPUT
	LEA DX,SR;输入字符串
	CALL INPUT
	LEA DX,TS2;输出提示字符串
	CALL OUTPUT
	OUTPUTSTR SR
	LEA DX, HC
	CALL OUTPUT
	LEA DX, FI
	CALL OUTPUT
	LEA DX,HC
	CALL OUTPUT
	CALL FINISH 
	RET 
MAIN ENDP
INPUT PROC
	MOV AH,0AH
	INT 21H
	RET 
INPUT ENDP 
OUTPUT PROC;终端输出过程
	MOV AH, 09H
	INT 21H
	RET
OUTPUT ENDP
FINISH PROC;程序按任意键结束过程
	MOV AH,0
	INT 16H
	MOV AH,4CH
	INT 21H
	RET 
FINISH ENDP
CODE ENDS
	END MAIN 